name: Go package

on:
  push:
    branches:
      - main
      - development
      - release
  pull_request:
    branches:
      - main
      - development
      - release
  release:
    branches:
      - main
      - development
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'

      - name: Install deps
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Build
        run: go build -v .

      - name: Vet and lint
        run: |
          go vet .
          golint .
